name: generate-repo

run-name: "Generate repo: ${{ inputs.NAME }}"

on:

  workflow_dispatch:
    inputs:
      NAME:
        description: 'name:'
        type: string
        required: true
      DESCRIPTION:
        description: 'description:'
        type: string
        required: true

permissions:
  contents: read
  id-token: write

defaults:
  run:
    shell: bash

jobs:

  create-repo:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout github-management
        uses: actions/checkout@v6
      -
        uses: actions/create-github-app-token@v3
        id: fetch-app-token
        with:
          client-id: ${{ secrets.ADMIN_APP_CLIENT_ID }}
          private-key: ${{ secrets.ADMIN_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      -
        name: Create new repository
        env:
          GH_TOKEN: ${{ steps.fetch-app-token.outputs.token }}
        run: |
          echo "::group::Generate repository"
          gh api /repos/${{ github.repository_owner }}/template/generate \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -F "owner=${{ github.repository_owner }}" \
            -F "name=${{ inputs.NAME }}" \
            -F "description=${{ inputs.DESCRIPTION }}" \
            -F "include_all_branches=false" \
            -F "private=false"
          echo "::endgroup::"

          echo "::group::Setup repository settings"
          gh api /repos/${{ github.repository_owner }}/${{ inputs.NAME }} \
            -X PATCH \
            -F visibility=public \
            -F allow_squash_merge=true \
            -F allow_merge_commit=false \
            -F allow_rebase_merge=false \
            -F allow_auto_merge=true \
            -F delete_branch_on_merge=true \
            -F squash_merge_commit_title=PR_TITLE \
            -F squash_merge_commit_message=PR_BODY
          echo "::endgroup::"

          echo "::group::Create PR ruleset"
          cat create-repo/ruleset.yml \
            | yq -o=json -I2 '.' \
            | gh api /repos/${{ github.repository_owner }}/${{ inputs.NAME }}/rulesets \
              -X POST \
              --input -
          echo "::endgroup::"

          echo "::notice::Created https://github.com/${{ github.repository_owner }}/${{ inputs.NAME }}"
